name = "pdf-ocr-backend"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[vars]
# GEMINI_API_KEY will be set via wrangler secret put or in .dev.vars for local dev

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "pdf-ocr-db"
database_id = "a8a0473b-0f07-436f-8a24-9dc5818296f8"
